version: '3.5'

services:
  #################################### NGINX + OPA ####################################

  nginx:
    image: nginx:1.21.4
    volumes:
      - "./kafka-oauth-strimzi/bundles:/usr/share/nginx/html"
    ports:
      - "80:80"
  opa:
    image: openpolicyagent/opa:0.35.0-rootless
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--set=decision_logs.console=true"
      - "--set=services.authz.url=http://nginx"
      - "--set=bundles.authz.service=authz"
      - "--set=bundles.authz.resource=bundle.tar.gz"
    depends_on:
      - nginx
  #################################### KAFKA BROKER ####################################
  kafka:
    image: quay.io/strimzi/kafka:latest-kafka-2.8.1-arm64
    build: kafka-oauth-strimzi/kafka/target
    container_name: kafka
    command:
      - /bin/bash
      - /opt/kafka/start_without_wait.sh

    ports:
      - 9092:9092
      - 9093:9093

      # javaagent debug port
      #- 5005:5005

    environment:

      # Java Debug
      KAFKA_DEBUG: n
      #DEBUG_SUSPEND_FLAG: y
      #JAVA_DEBUG_PORT: 5005

      #
      # KAFKA Configuration
      #
      LOG_DIR: /home/kafka/logs

      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: CLIENT://kafka:9093, OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:SASL_PLAINTEXT, OUTSIDE:PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: OAUTHBEARER
      KAFKA_INTER_BROKER_LISTENER_NAME: OUTSIDE
      #KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
       #KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SSL
      KAFKA_SSL_SECURE_RANDOM_IMPLEMENTATION: SHA1PRNG
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""

      KAFKA_LISTENER_NAME_CLIENT_OAUTHBEARER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;"
      #KAFKA_LISTENER_NAME_CLIENT_OAUTHBEARER_SASL_LOGIN_CALLBACK_HANDLER_CLASS: io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler
      KAFKA_LISTENER_NAME_CLIENT_OAUTHBEARER_SASL_SERVER_CALLBACK_HANDLER_CLASS: com.celonis.kafka.oauth.server.JWTSymmetricChiperValidatorCallbackHandler
      KAFKA_LISTENER_NAME_REPLICATION_SSL_CLIENT_AUTH: requested

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO

      # Hydra JWT tokens don't contain token type claim, therefore type check has to be skipped
      #OAUTH_CHECK_ACCESS_TOKEN_TYPE: "false"
      OAUTH_JWT_HMAC_SECRET_KEY: bananas
      OAUTH_USERNAME_CLAIM: sub

      # OPA Authorizer settings
      # Set cache expiry to low value for development in order to see decisions
      KAFKA_OPA_AUTHORIZER_CACHE_EXPIRE_AFTER_SECONDS: 10
      KAFKA_OPA_AUTHORIZER_URL: http://opa:8181/v1/data/kafka/authz/allow
      KAFKA_AUTHORIZER_CLASS_NAME: org.openpolicyagent.kafka.OpaAuthorizer
      CLASSPATH: "/opt/kafka/libs/*"
    volumes:
      - "./kafka-oauth-strimzi/plugin:/plugin"
      #- "./kafka-oauth-strimzi/certificates:/opt/kafka/config/"
    depends_on:
      - zookeeper
      - opa
    restart: on-failure

  zookeeper:
    image: strimzi/example-zookeeper
    build: kafka-oauth-strimzi/zookeeper/target
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - LOG_DIR=/home/kafka/logs
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181